spring:
  config:
    active:
      on-profile: "qa"

build:
  version: "3.0"

studenttracker:
  message: "Welcome to ABs Studentschedule related QA APIs "
  contactDetails:
    name: "Trunks - Developer"
    email: "goku@dbz.com"
  onCallSupport:
    - (555) 555-1231
    - (555) 523-1342