spring:
  config:
    active:
      on-profile: "prod"

build:
  version: "0.0"

studenttracker:
  message: "Welcome to ABs Studentschedule related PROD APIs "
  contactDetails:
    name: "Goku - Developer"
    email: "goku@dbz.com"
  onCallSupport:
    - (555) 555-1231
    - (555) 523-1342